_BASE_: "Base-SparseInst.yaml"

MODEL:
  # SPARSE_INST: 
  #   DATASET_MAPPER: None # 不datasetmapper 
  # WEIGHTS: "pretrained_models/resnet50d_ra2-464e36ba.pth"
  # WEIGHTS: "D:\\project_python\\SparseInst\\output\\aaaresnet3d_bs8_cocopretrain_jiangcaiyang\\model_0004999.pth"

  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_vd3d_backbone"
  RESNETS:
    DEFORM_ON_PER_STAGE: [2, False, True, True] # dcn on res4, res5
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (1024, 1024)
  MASK_FORMAT: "polygon"
  MAX_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 1024
  MIN_SIZE_TRAIN:
  - 1024
  MIN_SIZE_TRAIN_SAMPLING: choice
  RANDOM_FLIP: horizontal

OUTPUT_DIR: "output/a2kinput/"
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.00000625
  # IMS_PER_BATCH: 1
  # BASE_LR: 0.00000078125
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: []
  PROPOSAL_FILES_TRAIN: []
  TEST:
  - coco_rootair_train_2048
  TRAIN:
  - coco_rootair_train_2048
  # - coco_rootair_val
