_BASE_: "Base-SparseInst.yaml"
MODEL:
  # SPARSE_INST: 
  #   DATASET_MAPPER: None # 不datasetmapper 
  # WEIGHTS: "pretrained_models/resnet50d_ra2-464e36ba.pth"
  WEIGHTS: "pretrained_models//sparse_inst_r50vd_dcn_giam_aug_67dc06.pth"
  
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_vd_backbone"
  RESNETS:
    DEFORM_ON_PER_STAGE: [False, False, True, True] # dcn on res4, res5
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  MASK_FORMAT: "polygon"

OUTPUT_DIR: "output/aaatest_bs8_pretrained.tmp/"
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00000625
  # IMS_PER_BATCH: 1
  # BASE_LR: 0.00000078125
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: []
  PROPOSAL_FILES_TRAIN: []
  TEST:
  - coco_rootair_val
  TRAIN:
  - coco_rootair_train
  # - coco_rootair_val
