_BASE_: "Base-SparseInst.yaml"

MODEL:
  # SPARSE_INST: 
  #   DATASET_MAPPER: None # 不datasetmapper 
  # WEIGHTS: "pretrained_models/resnet50d_ra2-464e36ba.pth"
  # WEIGHTS: "D:\\project_python\\SparseInst\\output\\aaaresnet3d_bs8_cocopretrain_jiangcaiyang\\model_0004999.pth"
  # WEIGHTS: "D:\\project_python\\SparseInst\\output\\a2kinput_ori_downchannel_retry_re\\model_0004999.pth"
  # WEIGHTS: 'D:\\project_python\\SparseInst\\output\\aaaresnet3d_bs8_cocopretrain_jiangcaiyang\\model_0004999.pth' # 这个得到好的结果
  WEIGHTS: "D:\\project_python\\SparseInst\\pretrained_models\\sparse_inst_r50vd_dcn_giam_aug_67dc06.pth"

  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_vd3d_down_large_backbone"
  RESNETS:
    DEFORM_ON_PER_STAGE: [2, False, True, True] # dcn on res4, res5

INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  MASK_FORMAT: "polygon"

OUTPUT_DIR: "output_3d_rootair/base_2FTT/"
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00000625 # bs 8
  CHECKPOINT_PERIOD: 400
  # IMS_PER_BATCH: 1
  # BASE_LR: 0.00000078125
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: []
  PROPOSAL_FILES_TRAIN: []
  TEST:
  - coco_rootair_train
  TRAIN:
  - coco_rootair_train
  # - coco_rootair_val


TEST:
  EVAL_PERIOD: 733000